name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        contracts:
          - azns_registry
          - azns_fee_calculator
          - azns_name_checker
          - azns_merkle_verifier

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - run: rustup toolchain install stable --profile minimal
    - name: Install rust-src
      run: rustup component add rust-src
    - name: Install dylint-link
      run: cargo install dylint-link
    - name: Install Cargo Contract
      run: cargo install cargo-contract --force --locked --version 2.0.1
    - name: Build
      run: cargo contract build --verbose --manifest-path ${{ matrix.contracts }}/Cargo.toml
    - name: Run tests
      run: cargo test --workspace -- --nocapture
