name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - contract build
          - test
    env:
      CONTRACTS: "azns_registry azns_fee_calculator azns_name_checker azns_merkle_verifier azns_router"

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2.2.0
    - run: rustup toolchain install stable --profile minimal
    - name: Install rust-src
      run: rustup component add rust-src
    - name: Install dylint-link
      run: cargo install dylint-link
    - name: Install Cargo Contract
      run: cargo install cargo-contract --force --locked --version 3.2.0
    - name: Run ${{ matrix.job }}
      run: |
        for contract in ${CONTRACTS}; do
          echo "Processing contract: $contract";
          cargo ${{ matrix.job }} --verbose --manifest-path=src/$contract/Cargo.toml;
        done
